export const CONSTANTS =  {
    MONGODB_CONNECTION: 'MONGODB_CONNECTION',
    CAR_PARK_MODEL: 'CAR_PARK_MODEL',
    PARKING_LOT_MODEL: 'PARKING_LOT_MODEL',
    RESERVATION_MODEL: 'RESERVATION_MODEL',
    DATE_FORMAT: 'YYYY-MM-DD HH:mm'
}